require('./test/pack')
require('./test/package')
require('./test/coverage')
require('./test/document')
require('./test/markers')
require('./test/answers')
require('./test/mutants')
require('./test/regenerate')
