name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  security:
    runs-on: ubuntu-latest
    name: Security
    steps:
      - uses: holepunchto/actions/security-base@v1
  lint:
    runs-on: ubuntu-24.04
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    runs-on: ubuntu-24.04
    name: Test
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: npm test
